### ISSUE TITLE
登录以后点击帖子回复没有响应 console脚本显示有未加载的内容

### ISSUE THREAD

**Issue by w2689385876** [arrking/cnodebb#53]
未加载的脚本及报错如下 ：
nodebb.min.js:9 Uncaught SyntaxError: Unexpected end of input
rockq.org/:37 Uncaught ReferenceError: require is not defined
rockq.org/:1649 Uncaught ReferenceError: require is not defined

**Comment by hailiang-wang** [comment]
不能完整的下载这个文件。

https://rockq.org/nodebb.min.js?c0c98c55-d2df-4f88-bcbb-b539288770aa

**Comment by hailiang-wang** [comment]
Uncaught SyntaxError: Unexpected end of input

**Comment by hailiang-wang** [comment]
# nginx

```
cache - /var/lib/nginx/proxy , 有权限
user in nginx.conf - www-data
```

**Comment by hailiang-wang** [comment]
磁盘空间不足，导致nginx没有地方缓存文件，sendfile，清理一下磁盘，问题解决。
